#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")"
export BASE="$PWD"
echo $BASE

vim -Nu <(cat << EOF
filetype off
set rtp+=~/.vim/plugged/vader.vim
set rtp+=../vader.vim
set rtp+=..
filetype plugin indent on
syntax enable
EOF) +Vader!*
