" Needed for a code coverage
profile start /tmp/vim-profile.txt
profile! file ../*

filetype off
set rtp+=~/.vim/plugged/vader.vim
set rtp+=~/.fzf
set rtp+=~/.vim/plugged/fzf.vim
set rtp+=..
set rtp+=../after
filetype plugin indent on
syntax enable

